import { execFileSync } from "node:child_process";
import {
  copyFileSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const desktopRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const tauriRoot = join(desktopRoot, "src-tauri");
const trayRoot = join(tauriRoot, "assets", "tray");
const generatedRoot = join(trayRoot, "generated");
const iconsRoot = join(tauriRoot, "icons");
const tauriExecutable = join(
  desktopRoot,
  "node_modules",
  ".bin",
  process.platform === "win32" ? "tauri.cmd" : "tauri",
);

const master = readFileSync(join(trayRoot, "plankton-mark.svg"), "utf8");
const silhouetteMatch = master.match(
  /<g id="plankton-silhouette">([\s\S]*?)<\/g>/,
);
if (!silhouetteMatch) {
  throw new Error("plankton-mark.svg is missing #plankton-silhouette");
}
const silhouette = silhouetteMatch[1].trim();
const markPath = silhouette.match(/\bd="([^"]+)"/)?.[1];
if (!markPath) {
  throw new Error("plankton-mark.svg is missing its silhouette path");
}
const brandRed = "#e92339";
const brandRoot = join(desktopRoot, "src", "generated");
mkdirSync(brandRoot, { recursive: true });
writeFileSync(
  join(brandRoot, "planktonMark.ts"),
  `// Generated by scripts/generate-icons.mjs from plankton-mark.svg.\nexport const planktonMarkPath =\n  ${JSON.stringify(markPath)};\n`,
);

function standaloneSvg(markup) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">\n${markup}\n</svg>\n`;
}

function coloredSilhouette(color) {
  return silhouette.replaceAll("#000000", color);
}

function appTileMarkup() {
  return [
    `  <rect width="64" height="64" rx="14" fill="${brandRed}"/>`,
    '  <g transform="translate(7 7) scale(.78125)">',
    coloredSilhouette("#ffffff")
      .split("\n")
      .map((line) => `  ${line}`)
      .join("\n"),
    "  </g>",
  ].join("\n");
}

const spinnerDots = [
  [32, 10],
  [47.6, 16.4],
  [54, 32],
  [47.6, 47.6],
  [32, 54],
  [16.4, 47.6],
  [10, 32],
  [16.4, 16.4],
];

function spinnerFrame(color, activeDot) {
  const dots = spinnerDots
    .map(([cx, cy], index) => {
      const offset =
        (index - activeDot + spinnerDots.length) % spinnerDots.length;
      const opacity = [1, 0.72, 0.5, 0.32, 0.2, 0.14, 0.1, 0.07][offset];
      return `  <circle cx="${cx}" cy="${cy}" r="4.5" fill="${color}" fill-opacity="${opacity}"/>`;
    })
    .join("\n");
  return standaloneSvg(dots);
}

function write(relativePath, content) {
  const outputPath = join(trayRoot, relativePath);
  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, content);
}

const publicRoot = join(desktopRoot, "public");
mkdirSync(publicRoot, { recursive: true });
writeFileSync(join(publicRoot, "favicon.svg"), standaloneSvg(appTileMarkup()));
for (const [variant, color] of [
  ["red", brandRed],
  ["white", "#ffffff"],
]) {
  writeFileSync(
    join(publicRoot, `plankton-mark-${variant}.svg`),
    standaloneSvg(coloredSilhouette(color)),
  );
}

write(
  "macos/plankton-trayTemplate.svg",
  standaloneSvg(coloredSilhouette("#000000")),
);
write(
  "windows/plankton-tray-light.svg",
  standaloneSvg(coloredSilhouette("#111827")),
);
write(
  "windows/plankton-tray-dark.svg",
  standaloneSvg(coloredSilhouette("#ffffff")),
);
write("windows/plankton-taskbar.svg", standaloneSvg(appTileMarkup()));
write(
  "macos/plankton-app.svg",
  standaloneSvg(
    [
      '  <g transform="translate(7 7) scale(.78125)">',
      appTileMarkup()
        .split("\n")
        .map((line) => `  ${line}`)
        .join("\n"),
      "  </g>",
    ].join("\n"),
  ),
);

for (let frame = 0; frame < spinnerDots.length; frame += 1) {
  write(
    `macos/plankton-tray-spinnerTemplate-${frame}.svg`,
    spinnerFrame("#000000", frame),
  );
  write(
    `windows/plankton-tray-spinner-light-${frame}.svg`,
    spinnerFrame("#111827", frame),
  );
  write(
    `windows/plankton-tray-spinner-dark-${frame}.svg`,
    spinnerFrame("#ffffff", frame),
  );
}

function rasterize(sourcePath, outputs) {
  const temporaryOutput = mkdtempSync(join(tmpdir(), "plankton-icons-"));
  try {
    const sizes = [...new Set(outputs.map(({ size }) => size))];
    execFileSync(
      tauriExecutable,
      [
        "icon",
        sourcePath,
        "--output",
        temporaryOutput,
        ...sizes.flatMap((size) => ["--png", String(size)]),
      ],
      { cwd: desktopRoot, stdio: "inherit" },
    );
    for (const { size, destination } of outputs) {
      mkdirSync(dirname(destination), { recursive: true });
      copyFileSync(join(temporaryOutput, `${size}x${size}.png`), destination);
    }
  } finally {
    rmSync(temporaryOutput, { recursive: true, force: true });
  }
}

rasterize(join(trayRoot, "macos", "plankton-trayTemplate.svg"), [
  {
    size: 32,
    destination: join(generatedRoot, "macos", "plankton-trayTemplate.png"),
  },
  {
    size: 64,
    destination: join(generatedRoot, "macos", "plankton-trayTemplate@2x.png"),
  },
]);

for (let frame = 0; frame < spinnerDots.length; frame += 1) {
  rasterize(
    join(trayRoot, "macos", `plankton-tray-spinnerTemplate-${frame}.svg`),
    [
      {
        size: 32,
        destination: join(
          generatedRoot,
          "macos",
          `plankton-tray-spinnerTemplate-${frame}.png`,
        ),
      },
      {
        size: 64,
        destination: join(
          generatedRoot,
          "macos",
          `plankton-tray-spinnerTemplate-${frame}@2x.png`,
        ),
      },
    ],
  );
}

for (const variant of ["light", "dark"]) {
  rasterize(join(trayRoot, "windows", `plankton-tray-${variant}.svg`), [
    {
      size: 32,
      destination: join(
        generatedRoot,
        "windows",
        `plankton-tray-${variant}-32.png`,
      ),
    },
    {
      size: 64,
      destination: join(
        generatedRoot,
        "windows",
        `plankton-tray-${variant}.png`,
      ),
    },
  ]);

  for (let frame = 0; frame < spinnerDots.length; frame += 1) {
    rasterize(
      join(
        trayRoot,
        "windows",
        `plankton-tray-spinner-${variant}-${frame}.svg`,
      ),
      [
        {
          size: 32,
          destination: join(
            generatedRoot,
            "windows",
            `plankton-tray-spinner-${variant}-32-${frame}.png`,
          ),
        },
        {
          size: 64,
          destination: join(
            generatedRoot,
            "windows",
            `plankton-tray-spinner-${variant}-${frame}.png`,
          ),
        },
      ],
    );
  }
}

execFileSync(
  tauriExecutable,
  [
    "icon",
    join(trayRoot, "windows", "plankton-taskbar.svg"),
    "--output",
    iconsRoot,
  ],
  { cwd: desktopRoot, stdio: "inherit" },
);

if (process.platform === "darwin") {
  const temporaryOutput = mkdtempSync(join(tmpdir(), "plankton-icns-"));
  const rasterRoot = join(temporaryOutput, "png");
  const iconsetRoot = join(temporaryOutput, "Plankton.iconset");
  try {
    execFileSync(
      tauriExecutable,
      [
        "icon",
        join(trayRoot, "macos", "plankton-app.svg"),
        "--output",
        rasterRoot,
        ...[16, 32, 64, 128, 256, 512, 1024].flatMap((size) => [
          "--png",
          String(size),
        ]),
      ],
      { cwd: desktopRoot, stdio: "inherit" },
    );
    mkdirSync(iconsetRoot);
    for (const [sourceSize, iconsetName] of [
      [16, "icon_16x16.png"],
      [32, "icon_16x16@2x.png"],
      [32, "icon_32x32.png"],
      [64, "icon_32x32@2x.png"],
      [128, "icon_128x128.png"],
      [256, "icon_128x128@2x.png"],
      [256, "icon_256x256.png"],
      [512, "icon_256x256@2x.png"],
      [512, "icon_512x512.png"],
      [1024, "icon_512x512@2x.png"],
    ]) {
      copyFileSync(
        join(rasterRoot, `${sourceSize}x${sourceSize}.png`),
        join(iconsetRoot, iconsetName),
      );
    }
    copyFileSync(
      join(rasterRoot, "512x512.png"),
      join(iconsRoot, "macos-icon.png"),
    );
    execFileSync(
      "iconutil",
      ["-c", "icns", iconsetRoot, "-o", join(iconsRoot, "icon.icns")],
      { stdio: "inherit" },
    );
  } finally {
    rmSync(temporaryOutput, { recursive: true, force: true });
  }
}
